[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
bitcoincore-rpc = "0.18.0"
lazy_static = "1.4.0"
rocket = {version = "0.5.0-rc.2", features = ["json"] }
serde = "1.0.136"
